name: Test building docker image

on:
  push:
    branches:
      - main
      - staging
      - release/3.x
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
      - staging
      - release/3.x

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
